	AREA RESET, DATA, READONLY
	EXPORT __Vectors
 
__Vectors
	DCD 0x10001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0, =N
	LDR R2, =M
	MOV R3, #5
 
BACK LDR R1, [R0], #4
	STR R1, [R2], #4
	SUBS R3, #1
	BNE BACK
 
STOP B STOP
N DCD 0x1, 0x2, 0x3, 0x4, 0x5
	AREA mydata, DATA, READWRITE
M DCD 0
	END